remote_theme: pages-themes/minima
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [果不其然]
description: [My Eureka Moments]
# visitors count
counter: true