remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-mermaid

title: [EX BER BER TEA]
description: [A Study Group of Women Engineers]
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      enable_mermaid: true
